CREATE TABLE `users` (
	`id` BIGINT(20) NOT NULL,
	`name` VARCHAR(255) NOT NULL,
	`lastSeen` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`lastSpoke` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
	`lastStatus` VARCHAR(50) NULL DEFAULT NULL,
	`lastWritten` TEXT NULL,
	PRIMARY KEY (`id`),
	INDEX `name` (`name`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB;
